name: Patched Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch: {}
# on:
#   push:
#     paths:
#       - 'release-versions/*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Clone Upstream
        run: |
          LATEST_SHA=$(curl -sL https://api.github.com/repos/alacritty/alacritty/commits/master | jq -r ".sha" | cut -c1-8)
          cd /tmp
          git clone https://github.com/alacritty/alacritty.git
          cd alacritty
      # - name: Patch
      #   run: |
      #     cd /tmp/alacritty
      #     git apply $GITHUB_WORKSPACE/alacritty-win.patch
      # - name: Test
      #   run: |
      #     cd /tmp/alacritty
      #     cargo test --release
      - name: Patch
        run: |
          cd /tmp/alacritty
          # Strip anything but numbers/dots
          WIN_VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/[^0-9\.]//g')
          # Update version in wix config
          sed -ie "s/\\(<Product.*Version=\"\\).*\\(\" Manu.*\\)/\1$WIN_VERSION\2/" extra/windows/wix/alacritty.wxs
      - name: Build
        run: |
          cd /tmp/alacritty
          cargo build --release
      - name: Upload Portable Executable
        run: |
          cp /tmp/alacritty/target/release/alacritty.exe /tmp/Alacritty-${LATEST_SHA}-portable.exe
          ./.github/workflows/upload_asset.sh \
            /tmp/Alacritty-${LATEST_SHA}-portable.exe $GITHUB_TOKEN
      - name: Install WiX
        run: |
          cd /tmp/alacritty
          nuget install WiX
      - name: Create MSI Installer
        run: |
          ./WiX.*/tools/candle.exe -nologo -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./alacritty.wixobj" "extra/windows/wix/alacritty.wxs"
          ./WiX.*/tools/light.exe -nologo -ext WixUIExtension -ext WixUtilExtension \
            -out "/tmp/Alacritty-${LATEST_SHA}-installer.msi" -sice:ICE61 -sice:ICE91 \
            "./alacritty.wixobj"
      - name: Upload MSI Installer
        run: |
          ./.github/workflows/upload_asset.sh \
            /tmp/Alacritty-${LATEST_SHA}-installer.msi $GITHUB_TOKEN
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Alacritty-${LATEST_SHA}-installer.msi
            Alacritty-${LATEST_SHA}-portable.exe
