name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
# on:
#   push:
#     paths:
#       - 'release-versions/*'


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Download
        run: |
          LATEST_TAG=$(curl -sL https://api.github.com/repos/alacritty/alacritty/releases/latest | jq -r ".tag_name")
          cd /tmp
          git clone https://github.com/alacritty/alacritty.git
          cd alacritty
      # - name: Test
      #   run: |
      #     cd /tmp/alacritty
      #     cargo test --release
      - name: Build
        run: |
          cd /tmp/alacritty
          cargo build --release
      - name: Upload portable executable
        run: |
          cp /tmp/alacritty/target/release/alacritty.exe /tmp/Alacritty-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            /tmp/Alacritty-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN
      - name: Install WiX
        run: |
          cd /tmp/alacritty
          nuget install WiX
      - name: Crate msi installer
        run: |
          cd /tmp/alacritty
          ./WiX.*/tools/candle.exe -nologo -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./alacritty.wixobj" "extra/windows/wix/alacritty.wxs"
          ./WiX.*/tools/light.exe -nologo -ext WixUIExtension -ext WixUtilExtension \
            -out "/tmp/Alacritty-${GITHUB_REF##*/}-installer.msi" -sice:ICE61 -sice:ICE91 \
            "./alacritty.wixobj"
      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            /tmp/Alacritty-${GITHUB_REF##*/}-installer.msi $GITHUB_TOKEN
